### ISSUE TITLE
ipa-client-enroll fails to get https cert

### ISSUE THREAD

**Issue by slords** [adelton/webauthinfra#7]
The following line in ipa-client-enroll sometimes fails to get a certificate:

ipa-getcert request -k /etc/pki/tls/private/localhost.key -f $HTTP_CERT -N $HOSTNAME -K HTTP/$HOSTNAME -w

The error that is returned (on both idp and www) is:

Please verify that the certmonger service is still running.

**Comment by adelton** [comment]
Certmonger has been flaky in containers. I wonder if what you see is another symptom of the problem in https://bugzilla.redhat.com/show_bug.cgi?id=1656519?

**Comment by adelton** [comment]
The https://bugzilla.redhat.com/show_bug.cgi?id=1656519 was workarounded in freeipa-container via https://github.com/freeipa/freeipa-container/pull/283. With that, certmonger now behaves well.

@slords, can you check behaviour with the latest FreeIPA container image?

**Comment by adelton** [comment]
Let's assume it behaves now, closing.
