### ISSUE TITLE
Service 'www' has a link to service '55080:80' which is undefined

### ISSUE THREAD

**Issue by samqi** [adelton/webauthinfra#8]
I followed your instructions on your README and the docker-compose.yml file itself,
 but when I uncomment the lines for port 80 and 443 (ie:
```       # Uncomment the following if you want to be able to access the
        # www container on host's interface as well.
        # ports:
            - "55080:80"
            - "55443:443"
```

I get the following error doing `docker-compose build`:
```
Service 'www' has a link to service '55080:80' which is undefined.
```

**Comment by adelton** [comment]
I believe you need to uncomment the work `ports:` as well:

```
        # Uncomment the following if you want to be able to access the
        # www container on host's interface as well.
        ports:
           - "55080:80"
           - "55443:443"
```

Please let me know if it helps.

**Comment by samqi** [comment]
Ah yes, how could I have missed that important bit. Alright, this issue is fixed, but I encounter another issue. Let me open another issue and close this.
